name: my-ml-app

services:
  sentiment-analysis-app:
    image: 660838764267.dkr.ecr.eu-north-1.amazonaws.com/ml/sentiment-analysis-app:latest
    container_name: sentiment-app
    environment:
      - PORT=8000
    ports:
      - "5000:8000"
    volumes:
      - type: bind
        source: ./audit/
        target: /app/audit/
